#!/bin/sh

gsettings set org.gnome.shell.extensions.desktop-icons show-home 'false'
gsettings set org.gnome.shell.extensions.desktop-icons show-trash 'false'

functionDesktop(){
	rm ~/Desktop/*
	cp ~/.local/share/applications/InteraactionBoxLauncher.desktop ~/Desktop/
	gio set ~/Desktop/InteraactionBoxLauncher.desktop metadata::trusted true
	chmod a+x ~/Desktop/InteraactionBoxLauncher.desktop
}

functionBureau(){
	rm ~/Bureau/*
	cp ~/.local/share/applications/InteraactionBoxLauncher.desktop ~/Bureau/
	gio set ~/Bureau/InteraactionBoxLauncher.desktop metadata::trusted true
	chmod a+x ~/Bureau/InteraactionBoxLauncher.desktop
}

(functionBureau) || echo "Bureau icons don't work !"
(functionDesktop) || echo "Desktop icons don't work !"

exit 0
