#!/bin/sh

gsettings set org.gnome.shell.extensions.desktop-icons show-home 'false'
gsettings set org.gnome.shell.extensions.desktop-icons show-trash 'false'

cp ~/.local/share/applications/InteraactionBoxLauncher.desktop ~/Desktop

gio set ~/Desktop/InteraactionBoxLauncher.desktop metadata::trusted true
chmod a+x ~/Desktop/InteraactionBoxLauncher.desktop

rm ~/.config/autostart/desktopIcons.desktop

exit
