#!/bin/sh

gsettings set org.gnome.shell.extensions.desktop-icons show-home false
gsettings set org.gnome.shell.extensions.desktop-icons show-trash false

rm ~/.config/autostart/hideDesktopIcons.desktop
rm ~/Launcher/hideDesktopIcons
