#!/bin/sh

File=~/args.txt
valueFile=""

if [ -f "$File" ]; then
	
	while IFS= read -r line
	do
		valueFile="$line"
	done < "$File"
	
	if [ "$valueFile" = "true" ]; then
		
		zenity --info \
			--title="Finalisation de l'installation" \
			--text="Nous allons finaliser l'installation de l'interAACtionBox !" \
			--width=300 \
			--height=100 \
			--ok-label Suivant
			
		if [ $? -eq 1 ]; then
			exit 0
		else
			zenity --question \
				--title="Finalisation de l'installation" \
				--text="Avez-vous branché votre Eye Tracker ?" \
				--width=300 \
				--height=100 \
				--ok-label="Oui" \
				--cancel-label="Non"
				
			if [ $? -eq 1 ]; then
				zenity --info \
					--title="Finalisation de l'installation" \
					--text="Veuillez brancher votre Eye Tracker puis relancer l'application !" \
					--width=300 \
					--height=100 \
					--ok-label Suivant
			else
				zenity --info \
					--title="Finalisation de l'installation" \
					--text="Nous allons commencer la calibration de l'Eye Tracker !" \
					--width=300 \
					--height=100 \
					--ok-label Suivant
					
				if [ $? -eq 0 ]; then
					sh ~/Launcher/tobiiConfigLauncher.sh &
					tobii_config
					
					sh ~/InterAACtionBox_Interface-linux/bin/scripts/transition.sh ~/InterAACtionBox_Interface-linux/bin/images/transition.gif
					sh ~/InterAACtionGaze/bin/interAACtionGaze-linux-calibration.sh
					
					while IFS= read -r line
					do
						valueFile="$line"
					done < "$File"
	
					if [ "$valueFile" = "false" ]; then
						sh ~/Launcher/interaactionInterfaceLauncher.sh
					else
						exit 0
					fi
				else
					exit 0
				fi	
			fi
		fi	
		
	else
		sh ~/Launcher/interaactionInterfaceLauncher.sh	
	fi
	
else
	zenity --info \
			--title="Finalisation de l'installation" \
			--text="Nous allons finaliser l'installation de l'interAACtionBox !" \
			--width=300 \
			--height=100 \
			--ok-label Suivant
			
		if [ $? -eq 1 ]; then
			exit 0
		else
			zenity --question \
				--title="Finalisation de l'installation" \
				--text="Avez-vous branché votre Eye Tracker ?" \
				--width=300 \
				--height=100 \
				--ok-label="Oui" \
				--cancel-label="Non"
				
			if [ $? -eq 1 ]; then
				zenity --info \
					--title="Finalisation de l'installation" \
					--text="Veuillez brancher votre Eye Tracker puis relancer l'application !" \
					--width=300 \
					--height=100 \
					--ok-label Suivant
			else
				zenity --info \
					--title="Finalisation de l'installation" \
					--text="Nous allons commencer la calibration de l'Eye Tracker !" \
					--width=300 \
					--height=100 \
					--ok-label Suivant
					
				if [ $? -eq 0 ]; then
					sh ~/Launcher/tobiiConfigLauncher.sh &
					tobii_config
					
					sh ~/InterAACtionBox_Interface-linux/bin/scripts/transition.sh ~/InterAACtionBox_Interface-linux/bin/images/transition.gif
					sh ~/InterAACtionGaze/bin/interAACtionGaze-linux-calibration.sh
					
					while IFS= read -r line
					do
						valueFile="$line"
					done < "$File"
	
					if [ "$valueFile" = "false" ]; then
						sh ~/Launcher/interaactionInterfaceLauncher.sh
					else
						exit 0
					fi
				else
					exit 0
				fi	
			fi
		fi
fi

exit 0
