#!/bin/sh

File=~/args.txt
valueFile=""
actualLanguage=$LANG

title="Completing the installation"
text1="We are going to finalize the installation of interAACtionBox !"
text2="Please plug your Eye Tracker !"
text3="We will start calibrating your Eye Tracker !"
nextButton="Next"

if [ "$actualLanguage" = "fr_FR.UTF-8" ]; then
	title="Finalisation de l'installation"
	text1="Nous allons finaliser l'installation de l'interAACtionBox !"
	text2="Veuillez branché votre commande oculaire !"
	text3="Nous allons commencer la calibration de votre commande oculaire !"
	nextButton="Suivant"
fi

if [ -f "$File" ]; then
	
	while IFS= read -r line
	do
		valueFile="$line"
	done < "$File"
	
	if [ "$valueFile" = "true" ]; then
		
		zenity --info \
			--title="$title" \
			--text="$text1" \
			--width=300 \
			--height=100 \
			--ok-label "$nextButton"
			
		if [ $? -eq 1 ]; then
			exit 0
		else
			zenity --info \
				--title="$title" \
				--text="$text2" \
				--width=300 \
				--height=100 \
				--ok-label "$nextButton"
				
			if [ $? -eq 0 ]; then

				zenity --info \
					--title="$title" \
					--text="$text3" \
					--width=300 \
					--height=100 \
					--ok-label "$nextButton"
					
				if [ $? -eq 0 ]; then
					sh ~/Launcher/tobiiConfigLauncher.sh &
					tobii_config
					
					sh ~/InterAACtionBox_Interface-linux/bin/scripts/transition.sh ~/InterAACtionBox_Interface-linux/bin/images/transition.gif
					sh ~/InterAACtionGaze/bin/interAACtionGaze-linux-calibration.sh
					
					while IFS= read -r line
					do
						valueFile="$line"
					done < "$File"
	
					if [ "$valueFile" = "false" ]; then
						sh ~/Launcher/interaactionInterfaceLauncher.sh
					else
						exit 0
					fi
				else
					exit 0
				fi	
			fi
		fi	
		
	else
		sh ~/Launcher/interaactionInterfaceLauncher.sh	
	fi
	
else
	zenity --info \
			--title="$title" \
			--text="$text1" \
			--width=300 \
			--height=100 \
			--ok-label "$nextButton"
			
	if [ $? -eq 1 ]; then
		exit 0
	else
		zenity --info \
			--title="$title" \
			--text="$text2" \
			--width=300 \
			--height=100 \
			--ok-label "$nextButton"
				
		if [ $? -eq 0 ]; then

			zenity --info \
				--title="$title" \
				--text="$text3" \
				--width=300 \
				--height=100 \
				--ok-label "$nextButton"
					
			if [ $? -eq 0 ]; then
				sh ~/Launcher/tobiiConfigLauncher.sh &
				tobii_config
					
				sh ~/InterAACtionBox_Interface-linux/bin/scripts/transition.sh ~/InterAACtionBox_Interface-linux/bin/images/transition.gif
				sh ~/InterAACtionGaze/bin/interAACtionGaze-linux-calibration.sh
					
				while IFS= read -r line
				do
					valueFile="$line"
				done < "$File"
	
				if [ "$valueFile" = "false" ]; then
					sh ~/Launcher/interaactionInterfaceLauncher.sh
				else
					exit 0
				fi
			else
				exit 0
			fi	
		fi
	fi
fi

exit 0
