#!/usr/bin/env bash

# check if runing as root user
if [ "$EUID" -ne 0 ]; then
	echo -e "This script needs to run as root user, please use \"sudo ./install\" instead";
	exit 1;
fi

# check if plymouth themes directory exist
if [ ! -d "/usr/share/plymouth/themes" ]; then
	echo -e "\"/usr/share/plymouth/themes\" directory dose not exist, are you sure plymouth is installed and up to date?";
	exit 1;
fi

# coping theme in /usr/share/plymouth/themes/
cp -r `dirname $0`/interAACtionBox-Splash-Screen /usr/share/plymouth/themes/ ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occoured in moving `dirname $0`/interAACtionBox-Splash-Screen to /usr/share/plymouth/themes/" ;
	exit 1;
fi

# adding interAACtionBox-Splash-Screen in the list of aviable themes
update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/interAACtionBox-Splash-Screen/interAACtionBox-Splash-Screen.plymouth 100  &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occoured installing alternative in /usr/share/plymouth/themes/default.plymouth" ;
	exit 1;
fi

# setting interAACtionBox-Splash-Screen as default plymouth theme;
update-alternatives --set default.plymouth /usr/share/plymouth/themes/interAACtionBox-Splash-Screen/interAACtionBox-Splash-Screen.plymouth  &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occoured setting alternative in /usr/share/plymouth/themes/default.plymouth";
	exit 1;
fi

# updating Initial RAM File System
update-initramfs -u &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occoured executing \"update-initramfs -u\"";
	exit 1;
fi

exit 0;
